version: '3.8'

services:
  backend:
    image: redeermer
    build: .
    container_name: redeermer
    restart: always
    env_file: .env
    ports:
      - "1432:1432"
    volumes:
      - ./assets:/app/assets
    environment:
      - TZ=UTC