export enum CurrentStatus {
  RENOVATION = 'RENOVATION',
  UNDER_CONSTRUCTION = 'UNDER_CONSTRUCTION',
  COMPLETED = 'COMPLETED',
  IN_OPERATION = 'IN_OPERATION',
}

export enum LegalStatus {
  VERIFIED = 'VERIFIED',
  NOT_VERIFIED = 'NOT_VERIFIED',
}
