export enum ProjectFieldReviewEnum {
  PENDING = 'PENDING',
  VERIFIED = 'VERIFIED',
  REJECTED = 'REJECTED',
}

export enum FieldNameEnum {
  PROPERTY_TYPE = 'PROPERTY_TYPE',
  PROPERTY_SCALE = 'PROPERTY_SCALE',
  PROPERTY_OBJECTIVE = 'PROPERTY_OBJECTIVE',
  PROPERTY_ADVANTAGES = 'PROPERTY_ADVANTAGES',
  PROPERTY_LOCATION = 'PROPERTY_LOCATION',
  AREA = 'AREA',
  NUMBER_OF_FLOORS = 'NUMBER_OF_FLOORS',
  CURRENT_STATUS = 'CURRENT_STATUS',
  LEGAL_STATUS = 'LEGAL_STATUS',
  FLOOR_PLAN = 'FLOOR_PLAN',
  PROPOSED_VALUE = 'PROPOSED_VALUE',
}
