export enum ApiMessageKey {
  REGISTER_SUCCESS = 'Registration successful.',
  LOGIN_SUCCESS = 'Logged in successfully.',
  REFRESH_TOKEN_SUCCESS = 'Refresh token successfully.',
  FIND_ALL_USER_SUCCESS = 'Find all users successfully.',
  GET_USER_DETAIL_SUCCESS = 'Get user details successfully.',
  UPDATE_USER_SUCCESS = 'Update user successfully.',
  DELETE_USER_SUCCESS = 'Delete user successfully.',
  SEND_OTP_SUCCESS = 'Send OTP successfully.',
  VERIFY_OTP_SUCCESS = 'Verify OTP successfully.',
  ADD_EMAIL_INTO_WHITELIST_SUCCESS = 'Add email into whitelist successfully.',
  REMOVE_EMAIL_FROM_WHITELIST_SUCCESS = 'Remove email into whitelist successfully.',
  UPLOAD_FILES_SUCCESS = 'Upload files thành công.',
  UPLOAD_DOCUMENT_SUCCESS = 'Hồ sơ khách hàng đẩy lên thành công.',
  GET_DOCUMENT_SUCCESS = 'Lấy hồ sơ khách hàng thành công.',
}
