export enum ApiMessageKey {
  REGISTER_SUCCESS = 'Registration successful.',
  LOGIN_SUCCESS = 'Logged in successfully.',
  REFRESH_TOKEN_SUCCESS = 'Refresh token successfully.',
  FIND_ALL_USER_SUCCESS = 'Find all users successfully.',
  GET_USER_DETAIL_SUCCESS = 'Get user details successfully.',
  UPDATE_USER_SUCCESS = 'Update user successfully.',
  DELETE_USER_SUCCESS = 'Delete user successfully.',
  SEND_OTP_SUCCESS = 'Send OTP successfully.',
  VERIFY_OTP_SUCCESS = 'Verify OTP successfully.',
  ADD_EMAIL_INTO_WHITELIST_SUCCESS = 'Add email into whitelist successfully.',
  REMOVE_EMAIL_FROM_WHITELIST_SUCCESS = 'Remove email into whitelist successfully.',
  UPLOAD_FILES_SUCCESS = 'Upload files successfully.',
  UPLOAD_DOCUMENT_SUCCESS = 'Investor document upload successfully.',
  GET_DOCUMENT_SUCCESS = 'Get investor document successfully.',
  CREATE_CHECKOUT_LINK_SUCCESS = 'Create checkout link successfully.',
  RECEIVE_CHECKOUT_WEBHOOKS_SUCCESS = 'Receiving checkout webhook successfully.',
  CREATE_PROJECT_SUCCESS = 'Create project successfully.',
  UPDATE_PROJECT_SUCCESS = 'Update project successfully.',
  GET_DETAIL_PROJECT_SUCCESS = 'Get project detail successfully.',
  GET_ALL_PROJECT_INVESTMENT = 'Get all projects for investor successfully.',
  GET_ALL_PROJECT_LEGAL_PERSON = 'Get all projects for legal person successfully.',
  VERIFIED_MULTI_PROJECT_DOCUMENT_SUCCESS = 'Verified multi project document successfully.',
  VERIFIED_PROJECT_DOCUMENT_SUCCESS = 'Verified project document successfully.',
  DELETE_PROJECT_SUCCESS = 'Delete project successfully.',
}
